### ISSUE TITLE
Using nodeView with ProseMirror component

### ISSUE THREAD

**Issue by abingham** [ponymessenger/use-prosemirror#20]
I'm trying to use code mirror in a nodeView, essentially following the [example in ProseMirror's docs](https://prosemirror.net/examples/codemirror/). It's actually mostly working, but I still get the "unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering." when new codemirror instance is created (really, when it's rendered for the first time, I think).

I know this has been discussed at some length in #1 and #5, but I was wondering if the advice/techniques discussed there are still relevant. That is, should I use the portal approach outlined by @dminkovsky? He also said "it would be nice to include this inside the ProseMirror component so users don't have to deal with this problem", so I also wondered if it had been included.

If it'll help if I post some code, let me know and I'll do so.

**Comment by dminkovsky** [comment]
Hey @abingham, Thanks for opening this issue. The example you mention in #5 is still how I'm doing it. That that code has not been added to this library is because I've not had time and no one else has done it. But the way it's shown there, I get no warnings and I've had no issues with that approach.

**Comment by abingham** [comment]
Ok, it took some time, but I think I grok everything that's going on. And it all seems to work! Thanks for helping out.

I'd take a shot at adding this to use-prosemirror, but honestly my knowledge of all of the moving parts is still pretty superficial, and I wouldn't feel terribly confident. If this is still an open topic when I've been around the block a few more times, I may see if I can help out.

Thanks again.

**Comment by abingham** [comment]
I feel like I'm on the cusp of having everything working, but I'm still getting the 'flushDiscreteUpdates' warning. I'll try to describe the relevant details of my system in the hope that you can tell me if I'm doing something incorrectly.

First, I'm using react and redux. Critically, I'm storing the ProseMirror EditorState in the redux store because I have other, non-ProseMirror components that extract information from it. My basic setup for the ProseMirror component - i.e. before I added the CodeMirror stuff with nodeViews - looks like this:
```
const [_, setState] = useProseMirror(createEditorStateOpts());
const editorState = useSelector(
    (appState) => appState.writtenEditorState.editorState
  );
const dispatch = useDispatch();
return (
    <ProseMirror
        state={editorState}
        onChange={(newState) => dispatch(setEditorState(newState))}
    />
)
```
In other words, `onChange` simply sends the new states to the redux store. The changes to the store are propagated back to the ProseMirror component which re-renders based on the change. **This all seems to work properly.** I don't see any warnings, the data is always consistent and correct, etc.

*Question 1*: Is this a valid use of the ProseMirror component with redux, or am I fooling myself into thinking it's correct?

Assuming that's correct, I start to see problems when I try to use CodeMirror to render the 'code_block' nodes in my PM model. I'm using the same strategy you outlined in #5 with nodeViews and portals. And indeed, that all seems to work: CodeMirror renders in the right place with the right contents. The issues arise when I try to propagate the changes in CodeMirror down to the ProseMirror model.

The code doing that looks like this:
```
{nodeViewSpecs.map(({ getPos, node, view, el }) => {
        const render = (
          <CodeMirror
            value={node.textContent}
            onChange={(value, viewUpdate) => {
              // The transaction I create here seems to be correct.
              const tr = . . . calculate the transaction to apply to PM based on the CM changes . . .        
              const newState = view.state.apply(tr);

              // This is where things go wrong. Dispatching this state change to the redux store triggers the warning.
              dispatch(setEditorState(newState));
            }}
          />
        );
        return ReactDOM.createPortal(render, el);
      })}
```

That is, when CodeMirror reports a change, I create a new ProseMirror state based on it and send it through redux. For some reason that I can't sort out, this doesn't play nice with react and I get the 'flushDiscreteUpdates' warning.

So question 2: Is there anything that looks incorrect in what I've shown or described? Is this a sensible approach?

I recognize that perhaps [the CodeMirror component](https://uiwjs.github.io/react-codemirror/) is part of the problem, either because I'm using it wrong or it's broken somehow. But assuming that's not the case, does what I'm doing make sense vis a vis use-prosemirror? I'm pulling together a lot of unfamiliar threads right now, so any hints as to what might be going wrong would be appreciated!

**Comment by dminkovsky** [comment]
Hey @abingham sorry I am not able to help with this at this time. Hope you figure it out!

**Comment by abingham** [comment]
No worries. I think we're on track to sort it out, and it doesn't look like it's anything to do with use-prosemirror.

**Comment by supunkavinda** [comment]
Having the same "flushDiscreteUpdates" issue. @abingham Did you figure out any fix for that?

**Comment by dminkovsky** [comment]
What version of react are you using?

Пт, 4 марта 2022 г. в 12:00 AM, supunkavinda ***@***.***>:

**Comment by supunkavinda** [comment]
17.0.2

**Comment by abingham** [comment]
> Did you figure out any fix for that?

No, unfortunately we've had to try a different approach which doesn't use use-prosemirror or nested, dynamic react components. I don't remember the full line of reasoning, but essentially it seemed that we couldn't have a consistent system that nested react components using ProseMirror nodeviews and redux.

**Comment by dminkovsky** [comment]
Thanks for the info. I'm on 17.0.2 as well, and not experienced any `flushDiscreteUpdates` warnings given the technique described in #5. If you have the time/interest to create a code sandbox with a replica, please share. Thanks again.
